apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-example
policyDefaults:
  namespace: policies
  remediationAction: inform
  placement:
    labelSelector:
      matchExpressions:
      - key: environment
        operator: In
        values:
        - prod
policies:
  - name: openshift-gitops-installed
    manifests:
      - path: openshift-gitops-subscription.yaml
