apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-example
policyDefaults:
  namespace: default
  remediationAction: inform
  placement:
    labelSelector:
      matchExpressions:
        - key: environment
          operator: In
          values:
            - prod
            - qa
    selectorType: LabelSelector
policies:
  - name: openshift-gitops-installed
    manifests:
      - path: openshift-gitops-subscription.yaml
